Feature/ab 868 s3 reporter plugin
RiverSafeUK/eze-cli pull request #46
Opened 2021-12-18 15:06 UTC by mgonzales-rs

Adding a reporter for generate json report file and upload into a specific S3 bucket.

2021-12-20 09:06 UTC, Anthony-Mckale requested changes
small wee things, looks good

2021-12-20 09:06 UTC, Anthony-Mckale commented on tests/plugins/reporters/test_json_s3.py
> +        click_echo.assert_called_with("    Json Report file was uploaded successfully")
would recommend using eze-cli\tests\__test_helpers__\mock_helper.py::mock_print/mock_print_stderr

aka like eze-cli\tests\plugins\reporters\test_console.py

2021-12-20 13:01 UTC, Anthony-Mckale commented on eze/plugins/reporters/json_s3.py
> +            click.echo(f"""    Json Report file was uploaded successfully""")
major: click.echo/print debug messages need removed or refactored in the new logger util

2021-12-20 13:01 UTC, Anthony-Mckale commented on tests/plugins/reporters/test_json_s3.py
> +        # WARNING: this is a snapshot test, any changes to format will edit this and the snapshot will need to be updated
major: not a snapshot test, comments are not true

2021-12-20 13:02 UTC, Anthony-Mckale commented on eze/plugins/reporters/json_s3.py
> +        "AWS_ACCESS_KEY": {
minor: way to do env params (at the moment) is

```
        "AWS_ACCESS_KEY": {
            "type": str,
            "default": os.environ.get("AWS_ACCESS_KEY_ID") or None,
            "default_help_value": "ENVIRONMENT VARIABLE <AWS_ACCESS_KEY_ID>",
            "help_text": """aws access key of user authorized to upload files in bucket""",
        },
```

2021-12-20 13:26 UTC, Anthony-Mckale commented on tests/plugins/reporters/test_json_s3.py
> +from botocore.exceptions import ClientError
major: requirement missing from requirements.txt

2021-12-20 14:24 UTC, Anthony-Mckale commented on eze/plugins/reporters/json_s3.py
> +            "required": True,
imrpovement: could do with a reasonable default

2021-12-21 08:08 UTC, Anthony-Mckale commented on tests/plugins/reporters/test_json_s3.py
> +        try:
major: expected errors in pytest are caught with `pytest.raises`
https://docs.pytest.org/en/6.2.x/assert.html

```
        # When
        with pytest.raises(EzeConfigError) as thrown_exception:
            TrivyTool()
        # Then
        assert thrown_exception.value.message == expected_error_message
```

2021-12-21 09:12 UTC, Anthony-Mckale commented on eze/plugins/reporters/json_s3.py
> +        access_key = os.environ.get("ACCESS_KEY") or self.config["AWS_ACCESS_KEY"]
major: after reading docs more, feel it's unwise to duplicate the multiple systems behind aws configure

especially inconsidering the wonders of the complexity aka sso configure / session token etc

better to not handle credentials at all and let the boto3 library handle this via ~/.aws/credentials

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

2021-12-21 09:52 UTC, Anthony-Mckale commented on eze/plugins/reporters/json_s3.py
> +                Body=str(json_file),
major: apon verify uploads, unfortunately it's the path name not the content that's being uploaded!

![image](https://user-images.githubusercontent.com/585681/146909354-9615429e-aaba-4838-b67c-9601b602d6bb.png)

2021-12-21 14:29 UTC, michaelobineche-rs commented on tests/plugins/tools/test_semgrep.py
> +        assert expected_error_message == raised_error.value.message
Maybe re-order to raised_error.value.message == expected_error_message?

Just for visual consistency, since all the other tests are structured this way?

2021-12-21 15:04 UTC, michaelobineche-rs reviewed
Looks good, ran tests locally and everything works fine.

2021-12-21 15:41 UTC, Anthony-Mckale commented on tests/plugins/tools/test_semgrep.py
> +        assert expected_error_message == raised_error.value.message
lol good point will reorder it

2021-12-21 15:44 UTC, merged