Feature/ab 604 remote test gateway
RiverSafeUK/eze-cli pull request #6
Opened 2021-08-03 13:38 UTC by mgonzales-rs

Adds remote test calling function to Gateway

2021-08-04 09:59 UTC, Anthony-Mckale requested changes
needs some urls and apikey set in environment variables, might be worth adding flags for the url and apikey too

2021-08-04 09:59 UTC, Anthony-Mckale commented on eze/cli/commands/test_remote_commands.py
> +        api_url = "https://lff3adj48f.execute-api.eu-west-2.amazonaws.com/staging/v1/api/remote-scan"
FIXME: hardcoded url, should be EZE_REMOTE_SCAN_ENDPOINT or something similar as per
C:\dev\repos\eze-cli\eze\plugins\reporters\eze.py

2021-08-04 09:59 UTC, Anthony-Mckale commented on eze/cli/commands/test_remote_commands.py
> +    help="Especify the url of the remote repository to run scan. ex https://user:pass@github.com/repo-url",
Spelling ? : Especify

2021-08-05 14:11 UTC, mgonzales-rs commented on eze/cli/commands/test_remote_commands.py
> +        api_url = "https://lff3adj48f.execute-api.eu-west-2.amazonaws.com/staging/v1/api/remote-scan"
ok, nice

2021-08-05 14:12 UTC, mgonzales-rs commented on eze/cli/commands/test_remote_commands.py
> +    help="Especify the url of the remote repository to run scan. ex https://user:pass@github.com/repo-url",
:O spanish messing up with me

2021-08-05 14:14 UTC, mgonzales-rs commented on eze/cli/commands/test_remote_commands.py
> +                api_url, data=pretty_print_json(data).encode("utf-8"), headers={"Authorization": "---"}
cool.

2021-08-05 14:48 UTC, mgonzales-rs commented
Changes from ab#601 were merged so less commits are applicable here

2021-08-13 15:40 UTC, merged