AB#1054: cyclonedx unpinned assets
RiverSafeUK/eze-cli pull request #75
Opened 2022-03-06 17:28 UTC by Anthony-Mckale

2022-03-11 15:20 UTC, mgonzales-rs requested changes

2022-03-11 15:21 UTC, mgonzales-rs commented
cool: 
![image](https://user-images.githubusercontent.com/85571593/157896058-c0b9aa80-a1e0-48ab-addb-612996e8ae78.png)

2022-03-13 11:02 UTC, Anthony-Mckale commented on eze/plugins/tools/python_cyclonedx.py
>          for poetry_file in poetry_files:
so did it the otheer way, [warnings, cyclonedx_bom]  to [warnings, cyclonedx_bom, completed_process_stdout], testong on poetry examples

2022-03-13 11:07 UTC, Anthony-Mckale commented on eze/plugins/tools/python_cyclonedx.py
>          for poetry_file in poetry_files:
worked fine for me, if you could check again once i've merged

2022-03-13 11:08 UTC, Anthony-Mckale commented on eze/plugins/tools/python_cyclonedx.py
>          for poetry_file in poetry_files:
tested with eze-goats\goat-python\python-autorun

2022-03-13 11:21 UTC, merged